name: Compilar y Generar Javadoc

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Compilar el proyecto
        run: mvn clean compile

      - name: Generar Javadoc
        run: mvn javadoc:javadoc || echo "Error al generar Javadoc"

      - name: Mostrar contenido de target/
        run: ls -R target/ || echo "No se encontraron archivos en target/"


      - name: Mostrar contenido de target/site/
        run: ls -R target/site/ || echo "No se encontraron archivos en target/site/"

      - name: Subir Javadoc como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: javadoc
          path: target/site/apidocs/
